### ISSUE TITLE
How To Login ?

### ISSUE THREAD

**Issue by sepehrjb** [eyro-labs/flutter_parse#12]
There is a method for sign Up in ParseUser.class but Im not finding any ParseUser.class methods for login

**Comment by alann-maulana** [comment]
Didn't find login? Use this [ParseUser#signIn(username, password)](https://github.com/eyro-labs/flutter_parse/blob/enhancement/lib/src/parse_user.dart#L147) method to login

**Comment by sepehrjb** [comment]
> Didn't find login? Use this [ParseUser#signIn(username, password)](https://github.com/eyro-labs/flutter_parse/blob/enhancement/lib/src/parse_user.dart#L147) method to login

(FacePalm) . Sorry For Your Time
